apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: default
  labels:
    tier: backend
spec:
  selector:
    app: nginx
    tier: backend
  ports:
  - port: 80
    name: http
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default
  labels:
    app: nginx
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      tier: backend
  template:
    metadata:
      labels:
        app: nginx
        tier: backend
    spec:
      containers:
      - name: nginx
        image: nginx:1.18-alpine
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: www-storage
          mountPath: /srv/app/

      volumes:
      - name: www-storage
        persistentVolumeClaim:
          claimName: www-pvc
      - name: nginx-config-volume
        configMap:
          name: nginx-config