apiVersion: v1
kind: Service
metadata:
  name: nginx-php-fpm-service
  namespace: default
spec:
  selector:
    app: nginx-php-fpm
  ports:
  - port: 80
    name: http
    protocol: TCP
  - port: 9000
    name: php-fpm
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-php-fpm-deployment
  namespace: default
  labels:
    app: nginx-php-fpm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-php-fpm
  template:
    metadata:
      labels:
        app: nginx-php-fpm
    spec:
      containers:
      - name: php-fpm
        image: php:7.4-fpm
        ports:
        - containerPort: 9000
          name: php-fpm
          protocol: TCP
        volumeMounts:
        - name: www-storage
          mountPath: /srv/app/
      - name: nginx
        image: nginx:1.18-alpine
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: www-storage
          mountPath: /srv/app/

      volumes:
      - name: www-storage
        persistentVolumeClaim:
          claimName: www-pvc
      - name: nginx-config-volume
        configMap:
          name: nginx-config