apiVersion: v1
kind: Service
metadata:
  name: php-fpm-service
  namespace: default
  labels:
    tier: backend
spec:
  selector:
    app: php-fpm
    tier: backend
  ports:
  - port: 9000
    name: php-fpm
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm-deployment
  namespace: default
  labels:
    app: php-fpm
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-fpm
      tier: backend
  template:
    metadata:
      labels:
        app: php-fpm
        tier: backend
    spec:
      containers:
      - name: php-fpm
        image: php:7.4-fpm
        ports:
        - containerPort: 9000
          name: php-fpm
          protocol: TCP
        volumeMounts:
        - name: www-storage
          mountPath: /srv/app/
      
      volumes:
      - name: www-storage
        persistentVolumeClaim:
          claimName: www-pvc