apiVersion: v1
kind: Service
metadata:
  name: php-fpm-service
  namespace: default
  labels:
    tier: backend
spec:
  selector:
    app: php-fpm
    tier: backend
  ports:
  - port: 9000
    name: php-fpm
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm-deployment
  namespace: default
  labels:
    app: php-fpm
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-fpm
      tier: backend
  template:
    metadata:
      labels:
        app: php-fpm
        tier: backend
    spec:
      containers:
      - name: php-fpm
        image: php:7.4-fpm
        ports:
        - containerPort: 9000
          name: php-fpm
          protocol: TCP
        volumeMounts:
        - name: www-storage
          mountPath: /srv/app/
        
        # Init file using container lifecycle hooks
        # postStart -> after the container has started
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo '<?php echo phpinfo(); ?>' > /srv/app/index.php"]
      
      # Init file using init containers
      initContainers:
      - name: install
        image: busybox
        volumeMounts:
        - name: www-storage
          mountPath: /srv/app/
        command:
        - wget
        - "-O"
        - "/srv/app/info.php"
        - https://raw.githubusercontent.com/do-community/php-kubernetes/master/index.php
      
      volumes:
      - name: www-storage
        persistentVolumeClaim:
          claimName: www-pvc