apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-pvc
  namespace: default
spec:
  storageClassName: linode-block-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi